import { execFileSync, spawn } from "node:child_process"
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { connect } from "node:net"
import { homedir, hostname } from "node:os"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Command } from "commander"
import { createClient } from "../client.js"
import { resolveInstance } from "../instance.js"
import { printJson, printTable } from "../output.js"

// ---------------------------------------------------------------------------
// `sermon-admin worker` — manage the local ingestion worker daemon.
//
// The worker runs on THIS (residential-IP) machine because YouTube bot-blocks
// caption fetches from the server's datacenter IP. Two launchd agents:
//   com.sermonseek.tunnel  — SSH tunnel to prod Postgres (127.0.0.1:<port>)
//   com.sermonseek.worker  — `sermon-admin worker run` (the --serve daemon)
// Both KeepAlive, so once installed the queue drains with no manual commands.
// ---------------------------------------------------------------------------

const TUNNEL_LABEL = "com.sermonseek.tunnel"
const WORKER_LABEL = "com.sermonseek.worker"
const DEFAULT_PORT = 15432
const REMOTE_PG_PORT = 5432

const LAUNCH_AGENTS_DIR = join(homedir(), "Library", "LaunchAgents")
const LOG_DIR = join(homedir(), "Library", "Logs")
const TUNNEL_LOG = join(LOG_DIR, "sermonseek-tunnel.log")
const WORKER_LOG = join(LOG_DIR, "sermonseek-worker.log")

function defaultWorkerId(): string {
  return `${hostname().split(".")[0]}-local`
}

// Walk up from this file to the monorepo root (the dir with pnpm-workspace.yaml).
function repoRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url))
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, "pnpm-workspace.yaml"))) return dir
    const parent = dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  throw new Error("could not locate repo root (pnpm-workspace.yaml) from the CLI location")
}

function requireDarwin(): void {
  if (process.platform !== "darwin") {
    throw new Error("`worker` agent management uses launchd and is macOS-only.")
  }
}

function which(bin: string): string | null {
  try {
    return execFileSync("/usr/bin/which", [bin], { encoding: "utf8" }).trim() || null
  } catch {
    return null
  }
}

function parseEnvFile(path: string): Record<string, string> {
  const out: Record<string, string> = {}
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/)
    if (m?.[1]) out[m[1]] = m[2] ?? ""
  }
  return out
}

// Repoint a prod DATABASE_URL (…@host:port/db) at the local tunnel.
function tunnelDbUrl(prodUrl: string, port: number): string {
  return prodUrl.replace(/@[^/]+\//, `@127.0.0.1:${port}/`)
}

function xmlEscape(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

interface PlistOpts {
  throttle?: number
  workingDir?: string
  env?: Record<string, string>
  logPath?: string // used for both stdout and stderr
}

function plist(label: string, programArgs: string[], opts: PlistOpts = {}): string {
  const args = programArgs.map((a) => `    <string>${xmlEscape(a)}</string>`).join("\n")
  const extra: string[] = []
  if (opts.workingDir) {
    extra.push(`  <key>WorkingDirectory</key>\n  <string>${xmlEscape(opts.workingDir)}</string>`)
  }
  if (opts.throttle != null) {
    extra.push(`  <key>ThrottleInterval</key>\n  <integer>${opts.throttle}</integer>`)
  }
  if (opts.env) {
    const entries = Object.entries(opts.env)
      .map(([k, v]) => `    <key>${xmlEscape(k)}</key>\n    <string>${xmlEscape(v)}</string>`)
      .join("\n")
    extra.push(`  <key>EnvironmentVariables</key>\n  <dict>\n${entries}\n  </dict>`)
  }
  if (opts.logPath) {
    const p = xmlEscape(opts.logPath)
    extra.push(`  <key>StandardOutPath</key>\n  <string>${p}</string>`)
    extra.push(`  <key>StandardErrorPath</key>\n  <string>${p}</string>`)
  }
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by \`sermon-admin worker install\`. Do not edit by hand. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
${args}
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
${extra.join("\n")}
</dict>
</plist>
`
}

function plistPath(label: string): string {
  return join(LAUNCH_AGENTS_DIR, `${label}.plist`)
}

function launchctl(args: string[]): { code: number; out: string } {
  try {
    // Capture stderr (pipe) so "Could not find service" etc. doesn't leak to
    // the terminal during `status`.
    const out = execFileSync("/bin/launchctl", args, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    })
    return { code: 0, out }
  } catch (err) {
    const e = err as { status?: number; stdout?: Buffer; stderr?: Buffer }
    return {
      code: e.status ?? 1,
      out: `${e.stdout?.toString() ?? ""}${e.stderr?.toString() ?? ""}`,
    }
  }
}

interface AgentState {
  installed: boolean
  loaded: boolean
  pid?: number
  lastExit?: number
}

function agentState(label: string): AgentState {
  const installed = existsSync(plistPath(label))
  const { code, out } = launchctl(["list", label])
  if (code !== 0) return { installed, loaded: false }
  const pid = out.match(/"PID"\s*=\s*(\d+)/)?.[1]
  const lastExit = out.match(/"LastExitStatus"\s*=\s*(-?\d+)/)?.[1]
  return {
    installed,
    loaded: true,
    pid: pid ? Number(pid) : undefined,
    lastExit: lastExit ? Number(lastExit) : undefined,
  }
}

function tunnelReachable(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const sock = connect({ host: "127.0.0.1", port })
    const done = (ok: boolean) => {
      sock.destroy()
      resolve(ok)
    }
    sock.setTimeout(1500)
    sock.once("connect", () => done(true))
    sock.once("timeout", () => done(false))
    sock.once("error", () => done(false))
  })
}

function loadAgent(label: string): void {
  const path = plistPath(label)
  if (!existsSync(path)) throw new Error(`${label} is not installed. Run \`worker install\` first.`)
  launchctl(["unload", path]) // best-effort; ignore "not loaded"
  const { code, out } = launchctl(["load", path])
  if (code !== 0) throw new Error(`launchctl load ${label} failed: ${out.trim()}`)
}

function unloadAgent(label: string): void {
  const path = plistPath(label)
  if (existsSync(path)) launchctl(["unload", path])
}

/**
 * Restart a loaded agent in place.
 *
 * `kickstart -k` kills the running process and starts it again in one step.
 * The legacy unload/load pair is deprecated on current macOS and is unreliable
 * against a KeepAlive agent, which launchd may respawn between the two calls —
 * so an unload/load "restart" could leave the original process untouched.
 *
 * Falls back to loading the agent when it is not currently loaded, since
 * kickstart cannot start a service launchd does not know about.
 */
function restartAgent(label: string): void {
  const path = plistPath(label)
  if (!existsSync(path)) throw new Error(`${label} is not installed. Run \`worker install\` first.`)

  if (!agentState(label).loaded) {
    loadAgent(label)
    return
  }

  const { code, out } = launchctl(["kickstart", "-k", `gui/${process.getuid?.() ?? ""}/${label}`])
  if (code !== 0) throw new Error(`launchctl kickstart ${label} failed: ${out.trim()}`)
}

// --- install ---------------------------------------------------------------

function doInstall(opts: { key: string; target: string; port: number }): void {
  requireDarwin()
  const root = repoRoot()
  if (!existsSync(join(root, ".env.prod"))) {
    throw new Error(`.env.prod not found in ${root} — needed for DB creds and keys.`)
  }
  const node = process.execPath
  const ytDlp = which("yt-dlp")
  if (!ytDlp) throw new Error("yt-dlp not on PATH (the worker needs it for caption fetches).")
  const cliTsx = join(root, "apps", "cli", "node_modules", ".bin", "tsx")
  const cliEntry = join(root, "apps", "cli", "src", "index.ts")
  if (!existsSync(cliTsx)) throw new Error(`tsx not found at ${cliTsx} (run pnpm install).`)

  mkdirSync(LAUNCH_AGENTS_DIR, { recursive: true })
  mkdirSync(LOG_DIR, { recursive: true })

  // PATH for the worker agent — launchd does not inherit your shell PATH.
  const runPath = [
    dirname(node),
    dirname(ytDlp),
    "/opt/homebrew/bin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
  ].join(":")

  const tunnel = plist(
    TUNNEL_LABEL,
    [
      "/usr/bin/ssh",
      "-N",
      "-o",
      "ServerAliveInterval=30",
      "-o",
      "ServerAliveCountMax=3",
      "-o",
      "ExitOnForwardFailure=yes",
      "-o",
      "StrictHostKeyChecking=accept-new",
      "-i",
      opts.key,
      "-L",
      `${opts.port}:127.0.0.1:${REMOTE_PG_PORT}`,
      opts.target,
    ],
    { throttle: 10, logPath: TUNNEL_LOG },
  )

  // The worker agent runs the CLI's own `worker run` (foreground daemon), which
  // reads .env.prod at runtime — so no secrets land in the plist.
  const worker = plist(
    WORKER_LABEL,
    [cliTsx, cliEntry, "worker", "run", "--port", String(opts.port)],
    {
      workingDir: root,
      throttle: 15,
      env: { PATH: runPath },
      logPath: WORKER_LOG,
    },
  )

  writeFileSync(plistPath(TUNNEL_LABEL), tunnel)
  writeFileSync(plistPath(WORKER_LABEL), worker)
  loadAgent(TUNNEL_LABEL)
  loadAgent(WORKER_LABEL)

  console.log("Installed and started:")
  console.log(`  ${plistPath(TUNNEL_LABEL)}`)
  console.log(`  ${plistPath(WORKER_LABEL)}`)
  console.log("\nCheck:  sermon-admin worker status")
  console.log("Logs:   sermon-admin worker logs --follow")
}

// --- run (foreground daemon) ------------------------------------------------

function doRun(opts: { port: number }): void {
  const root = repoRoot()
  const envFile = join(root, ".env.prod")
  if (!existsSync(envFile)) throw new Error(`.env.prod not found in ${root}.`)
  if (!which("yt-dlp")) throw new Error("yt-dlp not on PATH (needed for caption fetches).")

  const prod = parseEnvFile(envFile)
  if (!prod.DATABASE_URL) throw new Error("DATABASE_URL missing from .env.prod.")

  const env: Record<string, string> = { ...process.env } as Record<string, string>
  env.DATABASE_URL = tunnelDbUrl(prod.DATABASE_URL, opts.port)
  env.CACHE_DIR = process.env.CACHE_DIR ?? join(root, ".cache-prod-worker")
  env.WORKER_API_URL = process.env.WORKER_API_URL ?? "https://sermonseek.ai"
  env.WORKER_ID = process.env.WORKER_ID ?? defaultWorkerId()
  // Only forward optional vars when non-empty: run.ts treats an empty (but
  // defined) LIMITED_INGEST_TOKEN_CAP / ENRICHMENT_MODEL as a hard error.
  for (const k of [
    "YOUTUBE_API_KEY",
    "OPENAI_API_KEY",
    "ENRICHMENT_MODEL",
    "WEB_BASE_URL",
    "LIMITED_INGEST_TOKEN_CAP",
    "ADMIN_API_KEY",
  ]) {
    if (prod[k]) env[k] = prod[k] as string
  }

  const workerTsx = join(root, "apps", "worker", "node_modules", ".bin", "tsx")
  const workerEntry = join(root, "apps", "worker", "src", "cli", "run.ts")
  console.error(`[worker run] --serve against 127.0.0.1:${opts.port} (WORKER_ID=${env.WORKER_ID})`)

  const child = spawn(workerTsx, [workerEntry, "--serve"], {
    cwd: join(root, "apps", "worker"),
    env,
    stdio: "inherit",
  })
  const forward = (sig: NodeJS.Signals) => child.kill(sig)
  process.on("SIGTERM", () => forward("SIGTERM"))
  process.on("SIGINT", () => forward("SIGINT"))
  child.on("exit", (code, signal) => {
    process.exit(signal ? 1 : (code ?? 0))
  })
  // The ref'd child + signal listeners keep the event loop alive until exit.
}

// --- status -----------------------------------------------------------------

interface ServerWorker {
  configured: boolean
  workerId: string
  found?: boolean
  status?: string
  stale?: boolean
  lastBeat?: string
  lastJob?: string | null
  otherLive?: number // live workers NOT matching our id (e.g. a leftover server worker)
}

async function serverWorkerRow(): Promise<ServerWorker> {
  const id = process.env.WORKER_ID ?? defaultWorkerId()
  let instance: ReturnType<typeof resolveInstance>
  try {
    instance = resolveInstance({})
  } catch {
    return { configured: false, workerId: id }
  }
  try {
    const health = await createClient(instance).health()
    // Match strictly by our worker id — never attribute another worker's
    // heartbeat (e.g. a leftover server worker) to this machine.
    const row = health.workers.find((w) => w.worker_id === id)
    const otherLive = health.workers.filter((w) => w.worker_id !== id && !w.stale).length
    if (!row) return { configured: true, workerId: id, found: false, otherLive }
    return {
      configured: true,
      workerId: id,
      found: true,
      status: row.status,
      stale: row.stale,
      lastBeat: row.last_beat_at,
      lastJob: row.last_job_id,
      otherLive,
    }
  } catch {
    return { configured: true, workerId: id, found: false }
  }
}

async function doStatus(opts: { port: number; json: boolean }): Promise<void> {
  const darwin = process.platform === "darwin"
  const tunnel = darwin ? agentState(TUNNEL_LABEL) : { installed: false, loaded: false }
  const worker = darwin ? agentState(WORKER_LABEL) : { installed: false, loaded: false }
  const reachable = await tunnelReachable(opts.port)
  const server = await serverWorkerRow()

  if (opts.json) {
    printJson({ darwin, tunnel, worker, tunnelPort: opts.port, tunnelReachable: reachable, server })
    return
  }

  const agentLine = (s: AgentState) => {
    if (!s.installed) return "not installed"
    if (!s.loaded) return "installed, not loaded"
    if (s.pid) return `running (pid ${s.pid})`
    return `loaded, not running${s.lastExit != null ? ` (last exit ${s.lastExit})` : ""}`
  }

  console.log("Local agents (launchd):")
  if (!darwin) {
    console.log("  (not macOS — launchd agents unavailable)")
  } else {
    printTable(
      ["Agent", "State"],
      [
        [TUNNEL_LABEL, agentLine(tunnel)],
        [WORKER_LABEL, agentLine(worker)],
      ],
    )
  }
  console.log("")
  console.log(
    `Tunnel 127.0.0.1:${opts.port} → prod Postgres: ${reachable ? "reachable" : "UNREACHABLE"}`,
  )
  console.log("")
  if (!server.configured) {
    console.log("Server heartbeat: (no instance configured — run `sermon-admin login`)")
  } else if (!server.found) {
    const others = server.otherLive ? ` (${server.otherLive} other live worker(s) registered)` : ""
    console.log(`Server heartbeat: worker "${server.workerId}" not registered yet${others}`)
  } else {
    const flag = server.stale ? "  [STALE]" : ""
    console.log(
      `Server heartbeat: worker "${server.workerId}" status=${server.status}${flag}  last_beat=${server.lastBeat}  last_job=${server.lastJob ?? "none"}`,
    )
  }
}

// --- logs --------------------------------------------------------------------

function doLogs(opts: { follow: boolean; tunnel: boolean; lines: number }): void {
  const file = opts.tunnel ? TUNNEL_LOG : WORKER_LOG
  if (!existsSync(file)) {
    console.error(`No log file yet at ${file} (has the worker been installed/started?)`)
    process.exit(1)
  }
  const args = ["-n", String(opts.lines)]
  if (opts.follow) args.push("-f")
  args.push(file)
  const child = spawn("/usr/bin/tail", args, { stdio: "inherit" })
  child.on("exit", (code) => process.exit(code ?? 0))
}

// --- command wiring ----------------------------------------------------------

function parsePort(v: string): number {
  const n = Number.parseInt(v, 10)
  if (!Number.isInteger(n) || n < 1 || n > 65535) throw new Error(`invalid --port "${v}"`)
  return n
}

function fail(err: unknown): never {
  console.error(err instanceof Error ? err.message : String(err))
  process.exit(1)
}

export function makeWorkerCommand(): Command {
  const cmd = new Command("worker").description("Manage the local ingestion worker daemon (macOS)")

  cmd
    .command("install")
    .description("Generate + load the launchd agents (SSH tunnel + --serve daemon)")
    .requiredOption("-i, --key <path>", "SSH private key for the tunnel")
    .requiredOption("--target <user@host>", "SSH target for the prod host")
    .option("--port <n>", "Local tunnel port for Postgres", parsePort, DEFAULT_PORT)
    .action((o: { key: string; target: string; port: number }) => {
      try {
        doInstall({ key: o.key, target: o.target, port: o.port })
      } catch (err) {
        fail(err)
      }
    })

  cmd
    .command("uninstall")
    .description("Unload and remove the launchd agents (logs are kept)")
    .action(() => {
      try {
        requireDarwin()
        unloadAgent(WORKER_LABEL)
        unloadAgent(TUNNEL_LABEL)
        for (const label of [WORKER_LABEL, TUNNEL_LABEL]) {
          if (existsSync(plistPath(label))) rmSync(plistPath(label))
        }
        console.log("Removed launchd agents.")
      } catch (err) {
        fail(err)
      }
    })

  cmd
    .command("start")
    .description("Load (start) both agents")
    .action(() => {
      try {
        requireDarwin()
        loadAgent(TUNNEL_LABEL)
        loadAgent(WORKER_LABEL)
        console.log("Started tunnel + worker.")
      } catch (err) {
        fail(err)
      }
    })

  cmd
    .command("stop")
    .description("Unload (stop) both agents")
    .action(() => {
      try {
        requireDarwin()
        unloadAgent(WORKER_LABEL)
        unloadAgent(TUNNEL_LABEL)
        console.log("Stopped worker + tunnel.")
      } catch (err) {
        fail(err)
      }
    })

  cmd
    .command("restart")
    .description("Restart both agents in place (picks up new code)")
    .action(() => {
      try {
        requireDarwin()
        restartAgent(TUNNEL_LABEL)
        restartAgent(WORKER_LABEL)
        console.log("Restarted tunnel + worker.")
      } catch (err) {
        fail(err)
      }
    })

  cmd
    .command("status")
    .description("Show launchd state, tunnel reachability, and the live server heartbeat")
    .option("--port <n>", "Local tunnel port to probe", parsePort, DEFAULT_PORT)
    .action(async (o: { port: number }, self: Command) => {
      const json = self.optsWithGlobals<{ json?: boolean }>().json ?? false
      try {
        await doStatus({ port: o.port, json })
      } catch (err) {
        fail(err)
      }
    })

  cmd
    .command("logs")
    .description("Tail the local worker log (use --tunnel for the SSH tunnel log)")
    .option("--follow", "Stream new lines until Ctrl-C")
    .option("--tunnel", "Show the tunnel log instead of the worker log")
    .option("--lines <n>", "Lines of history to print", parsePort, 200)
    .action((o: { follow?: boolean; tunnel?: boolean; lines: number }) => {
      try {
        doLogs({ follow: o.follow ?? false, tunnel: o.tunnel ?? false, lines: o.lines })
      } catch (err) {
        fail(err)
      }
    })

  cmd
    .command("run")
    .description("Run the --serve daemon in the foreground (used by the launchd agent)")
    .option("--port <n>", "Local tunnel port for Postgres", parsePort, DEFAULT_PORT)
    .action((o: { port: number }) => {
      try {
        doRun({ port: o.port })
      } catch (err) {
        fail(err)
      }
    })

  return cmd
}
