export { BOOKS, BOOKS_BY_ID, BOOK_LOOKUP } from "./books.js"
export type { Book } from "./books.js"
export { coord, lastVerse, display } from "./coord.js"
export type { Ref } from "./coord.js"
export { extract } from "./extract.js"
export type { ExtractedRef } from "./extract.js"
